services:
  restassured-tests:
    build: .
    container_name: restassured-container
    volumes:
      - ./reports:/app/reports
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
